SELECT TOP (1000) [IDDireccion]
      ,[IDUsuario]
      ,[Calle]
      ,[Numero]
      ,[Localidad]
      ,[Provincia]
      ,[CodigoPostal]
      ,[Observaciones]
      ,[EsPrincipal]
      ,[TipoDireccion]
      ,[FechaRegistro]
      ,[FechaModificacion]
      ,[Activo]
  FROM [EcommerceDB].[dbo].[Direcciones]
